### ISSUE TITLE
Cannot reach integrated Ducky Panel after fresh install

### ISSUE THREAD

**Issue by DuredhelFinceleb** [louis-lau/DuckyAPI#12]
Hi!

I've installed DuckyAPI
Put it on port 3001 since wildduck-webmail already uses this port
SERVE_DUCKYPANEL is set to true and BASE_URL to /api
Created a /var/log/DuckyAPI so I could start DuckyAPI like this
nohup npm start > /var/log/DuckyAPI/DuckyAPI.log 2> /var/log/DuckyAPI/DuckyAPI.error.log &
Maybe there's a smarter way to do this, I'll look into this later
I'll also need to ensure DuckyAPI is up after server restart

For now, no problem in create the admin user & the first user
But then when browsing to localhost:3001, FF says it cannot connect 
It's weird as "telnet localhost 3001" does respond but nothing happens when I do a "GET /" 
"GET /api" kicks me out immediately so I know that DuckyAPI is there
But it seems DuckyPanel is not there
Other weird thing: when I "netstat -nlp", I can see the node listening on IPV6 on :::3001 but I can't see anything listening on IPV4 on port 3001

**Comment by louis-lau** [comment]
Well this is very confusing. Working fine on my machine, but on a vps it doesn't work. Just like you describe. Let me find out why.

> Maybe there's a smarter way to do this

Systemd will do this :). And it will keep the logs for you as well.

> Other weird thing: when I "netstat -nlp", I can see the node listening on IPV6 on :::3001 but I can't see anything listening on IPV4 on port 3001

This seems to be the default for nodejs when listening on localhost. If ipv6 is available it will listen on it, otherwise on ipv4. It shouldn't really matter though. I expect you to put it behind a reverse proxy.

**Comment by louis-lau** [comment]
Actually, I found out I was being dumb. Maybe you are as well 😁? Because otherwise I can't repoduce this.

My mistake when installing it on a fresh VPS was to only uncomment `SERVE_DUCKYPANEL=false` instead of actually setting it to true.

I'll set that commented variable to true in the example configuration to avoid any confusion. I mean I even confused myself!

**Comment by DuredhelFinceleb** [comment]
Hi, 

Well I had `SERVER_DUCKYPANEL=true` in my config/production.env before reporting to you
That being said, I was still being dumb because I've tested with FF which runs... on my local workstation and not on the VPS of course 🤦🏾 
So I've got back to the server & tried with curl... and it works!
OK now I'll proxy this with nginx so I can access it properly 🙂
